export const apiEndpoints = {
    // Farm
    farm: "farm",
    createFarm: "farm",
    // Crop
    crop: "crop",
    createCrop: "crop",
    cropId: "cropid",
    // Soil
    soil: "soil",
    createSoil: "soil",
    // Field
    field: "field",
    createField: "field",
    // Machine
    machine: "machine",
    createMachine: "machine",
    // ProcessingType
    processingType: "processingType",
    createProcessingType: "processingType",
    // GrowingCropPeriod
    growingPeriod: "growingCropPeriod",
    // Processing
    processing: "processing",
    createProcessing: "processing",
    // Reports
    farmsWithMostMachines: "farms-with-most-machines",
    fieldCountPerFarmAndCrop: "field-count-per-farm-and-crop",
    mostCommonSoilPerFarm: "most-common-soil-per-farm",
    processingReport: "processing-report",
};
