export const routes = {
    login: "/login",
    register: "/register",
    profile: "/profile",
    service: "/service",
    farm: "/farm",
    field: "/field",
    soil: "/soil",
    crop: "/crop",
    processingType: "/processingType",
    machine: "/machine",
    processing: "/processing",
    reports: "/reports",
    contacts: "/contacts",
    notFound: "/*",
};
